### ISSUE TITLE
example does not play any sound

### ISSUE THREAD

**Issue by tomsoftware** [wothke/adplug-2.2.1#1]
Not sure what the problem is but your example does not play any sound?

Maybe it is because the AudioBufferSource.buffer is null? But the scriptprocessor_player.min.js is compressed and quite hard to debug :-( . May you can help? (tried with in Chrome and Firefox)

![audio](https://cloud.githubusercontent.com/assets/3290888/13654863/415f51f8-e65b-11e5-905d-0832e7f04f0c.png)

Thank you for your help.

the example on
http://www.wothke.ch/webaudio68/
works... but this
http://www.wothke.ch/AdLibido/
not :-(

PS: I would like to use your tool to play back the soundtrack of an old dos game.

**Comment by wothke** [comment]
I just tried the http://www.wothke.ch/AdLibido/ link and it works fine in FF41 and Chrome31. I cannot reproduce the problem. (PS: the uncompressed version of the generic player can be found here: https://github.com/wothke/webaudio-player-1.0)

**Comment by tomsoftware** [comment]
Helllo Wothke,

Sorry!!! Found the "bug" :-) ... the Sound only plays on one channel and I only use the other channel with my computer.

Thanks for all :-) and have a good time!
